# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-23 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huellita', '0002_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrado',
            name='dni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registrado',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
